##################################################
# Qubinode VM for Testing the qubinode-installer #
##################################################
qbn_rhel_vcpu: 4
qbn_rhel_memory: 2048
qbn_rhel_root_disk_size: 100G

qbn_rhel_extra_storage:
  - size: "500G"
    enable: "no"
