#!/usr/bin/env bash
set -E
set -o functrace

# Uncomment for debugging
#export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
#set -x

# Turn verbose off
_V=1

function config_err_msg () {
    cat << EOH >&2
  There was an error finding the full path to the qubinode-installer project directory.
EOH
}

# this function just make sure the script
# knows the full path to the project directory
# and runs the config_err_msg if it can't determine
# that start_deployment.conf can find the project directory
function setup_required_paths () {
    project_dir="`dirname \"$0\"`"
    project_dir="`( cd \"$project_dir\" && pwd )`"
    if [ -z "$project_dir" ] ; then
        config_err_msg; exit 1
    fi

    if [ ! -d "${project_dir}/playbooks/vars" ] ; then
        config_err_msg; exit 1
    fi
}

##       MAIN               ##
##############################

# load pre functions
teardown="false"
CURRENT_USER=$(whoami)
setup_required_paths

# Include all required functions
source "${project_dir}/lib/00_pre_functions.sh"
source "${project_dir}/lib/qubinode_utils.sh"
source "${project_dir}/lib/01_product_functions.sh"
source "${project_dir}/lib/qubinode_menu_options.sh"
source "${project_dir}/lib/setup_sudo.sh"
source "${project_dir}/lib/qubinode_userinput.sh"
source "${project_dir}/lib/qubinode_kvmhost.sh"
source "${project_dir}/lib/qubinode_idm.sh"
source "${project_dir}/lib/qubinode_ansible.sh"
source "${project_dir}/lib/qubinode_rhsm.sh"
source "${project_dir}/lib/qubinode_openshift3.sh"
source "${project_dir}/lib/qubinode_ocp4.sh"
source "${project_dir}/lib/qubinode_hardware_check.sh"
source "${project_dir}/lib/qubinode_openshift3_powermgt.sh"
source "${project_dir}/lib/qubinode_satellite.sh"
source "${project_dir}/lib/qubinode_tower.sh"


# Exit if this is executed as the root user
if is_root; then
    echo "Error: qubi-installer should be run as a normal user, not as root!"
    exit 1
fi

echo ""
echo ""
OPTIND=1
NUM_ARGS="$#"
ALL_ARGS="$@"

while getopts ":c:dvhm:p:a:" opt;
do
    case $opt in
        a) check_args;
           full_deploy=true
           ;;
        c) check_args
           check=true
           cluster=true
           cluster_opt=$OPTARG
           ;;
        d) check_args;
           teardown=true
           ;;
        h) display_help
           exit 1
           ;;
        m) check_args;
           qubinode_maintenance=true
           qubinode_maintenance_opt=$OPTARG;
           ;;
        p) check_args
           check=true
           qubinode_product=true
           qubinode_product_opt=$OPTARG
           ;;
        v) check_args;
           _V=1
           ;;
       --) shift; break;;
       -*) echo Unrecognized flag : "$1" >&2
           display_help
           exit 1
           ;;
       \?) echo Unrecognized flag : "$1" >&2
           display_help
           exit 1
           ;;
    esac
done
shift "$((OPTIND-1))"

# If not arguments pass, run default option to install OpenShift
if (( $OPTIND == 1 )) 
then
    cat < "${project_dir}/lib/docs/default_message"
    default_message=("Continue with the default installation" "Display the help menu")
    createmenu "${default_message[@]}"
    result=($(echo "${selected_option}"))
    if [ "A${result}" == "ADisplay" ]
    then
        display_help
    elif [ "A${result}" == "AContinue" ]
    then
        check_for_rhel_qcow_image
        qubinode_autoinstall_openshift
    else
        echo $result
        echo "Unknown issue, please run the installer again"
    fi
elif [ "A${qubinode_product}" == "Atrue" ] && [ "A${qubinode_maintenance}" == "Atrue" ]
then
    product_maintenance="${qubinode_maintenance_opt}"
    qubinode_product_deployment $qubinode_product_opt
elif [ "A${qubinode_maintenance}" == "Atrue" ]
then
    qubinode_maintenance_options
elif [ "A${qubinode_product}" == "Atrue" ]
then
    check_for_rhel_qcow_image
    qubinode_product_deployment $qubinode_product_opt
else
    display_help
fi

exit 0
