apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${PV}
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ${MODE}
  nfs:
    path: /var/lib/libvirt/images/${PV}
    server: ${PRIMARY_IP}
  persistentVolumeReclaimPolicy: Recycle