// NOTE: Qubinode git branching strategey 
= Qubinode Git branching  strategy
:toc: preamble
:numbered!:
[abstract]
== Introduction

This guide contains all the information needed to become a contributor on the Qubinode project. Please follow our git branching model so that everyone will have a pleasant experience contributing to this project.

== Branching and releasing

- *master* holds the latest production ready code
* Rules:
** Should be the same for every Git user

- *develop* holds latest changes for next release
* Rules:
** Merge to *master*  branch when all codes are stable 
** Tag *master* branch with new release number after merging from *develop* branch


- *feature* holds code for developed new features that will be merged in the next or future Qubinode release
* Rules:
** May branch off from the *develop* branch
** Must merge back to the *develop* branch
** Exists on developer's repository only
** Discarded once all code are merged to *develop* bramch

- *release* support preparation of a new production release. Use for minor changes or bugfixes 
* Rules:
** May branch off from the *develop* branch
** Must merge back to the *develop* and *master* branch
** Exists on developer's repository only

- *hotfix* Use to push a fix for an error in the *master* branch
* Rules:
** May branch off from *master* branch
** Must be merged back into *master* and *develop* branch

== Scenerios
=== Adding a new feature
A developer wants to add a new menu item as part of the current release

1. switch to the develop branch:
....
$ git checkout develop
....

2. fetch the latest code from the develop branch code:
....
$ git fetch develop
....

3. create new feature branch using nomenclature feature-<feature_description>
....
$ git checkout -b feature-new-menu develop
....

Code the new menu, finished features are merged back into develop branch

4. checkout the develop branch
....
$ git checkout develop
....

5. merge the new feature to the develop branch
....
$ git merge --no-ff feature-new-menu
....

6. delete the feature branch
....
$ git branch -d feature-new-menu
....

7. push changes to the develop branch
....
$ git push origin develop
....

8. do a merge request to the Qubinode repository
