---
- name: Deploy OpenShift 4.x Cluster
  hosts: localhost
  gather_facts: yes
  become: yes
  vars_files:
    - vars/all.yml
    - vars/vault.yml
    - vars/idm.yml
    - vars/kvm_host.yml
    - vars/ocp4.yml
  environment:
    IPA_HOST: "{{ idm_server_shortname }}.{{ internal_domain_name }}"
    IPA_USER: "{{ user_idm_admin }}"
    IPA_PASS: "{{ user_idm_password }}"

  tasks:
  - name: run the role ocp4_kvm_deployer
    import_role:
      name: ocp4_kvm_deployer
