---
- name: Checking if qcow image already exist {{ qcow_download_dir }}/{{ item.qcow_name }}
  when: (item.qcow_name is defined) and (item.qcow_name|length > 0)
  stat:
    path: "{{ qcow_download_dir }}/{{ item.qcow_name }}"
    get_checksum: no
    get_attributes: no
  register: qcow_exist

- name: Download QCOW Images
  when: (qcow_exist.stat.exists is defined) and (not qcow_exist.stat.exists)
  block:
    - name: Get download URL for {{ item.qcow_name }}
      uri:
        url: https://api.access.redhat.com/management/v1/images/{{ item.qcow_sha }}/download
        headers:
          accept: "application/json"
          Authorization: "Bearer {{ temp_token.json.access_token }}"
        method: GET
      register: download_url
       
    - name: Download {{ item.qcow_name }} from {{ download_url.url }}
      become: yes
      get_url:
        owner: "{{ admin_user }}"
        group: qemu
        url: "{{ download_url.url }}"
        dest: "{{ qcow_download_dir }}/{{ item.qcow_name }}"
        checksum: "sha256: {{ item.qcow_sha }}"
          
  rescue:
    - name: Could not download {{ item.qcow_name }} from {{ download_url.url }}
      debug:
        msg: "Download of {{ download_url.url }} from access.redhat.com has failed. Sometimes the service is just busy. Perhaps try manually download {{ item.qcow_name }} to {{ qcow_download_dir }}."

