---
- name: IdM server VM post removal cleanup
  hosts: localhost
  become: yes
  gather_facts: no
  vars_files:
    - vars/all.yml
    - vars/kvm_host.yml
    - vars/idm.yml
    - vars/vault.yml

  tasks:
    - name: check if resolv.conf backup file exists
      stat:
        path: "{{ project_dir }}/backups/resolv.conf"
      register: resolv_backup

    - name: update KVM host /etc/resolv.conf
      copy:
        src: "{{ project_dir }}/backups/resolv.conf"
        dest: /etc/resolv.conf  # link to /path/to/file
        follow: yes
      when: resolv_backup.stat.exists == True

    - name: REMOVE|ensure host is removed from inventory
      vars:
        vm_name: "{{ dns_server_vm.dns_name }}"
      lineinfile:
        path: "{{ inventory_file }}"
        regexp: "^{{ vm_name }}"
        state: absent
