---
- name: deploy IdM server
  hosts: ipaserver
  remote_user: admin
  become: true
  gather_facts: true
  vars_files:
    - vars/all.yml
    - vars/kvm_host.yml
    - vars/vault.yml
    - vars/idm.yml

  tasks:
    - name: Check if IdM is answering
      vars:
        vm_name: "{{ dns_server_vm.dns_name }}"
      uri:
        url: "https://{{ vm_name  }}.{{ domain }}/ipa/ui"
        user: "{{ idm_admin_user }}"
        password: "{{ idm_admin_password }}"
        force_basic_auth: yes
      register: idm_is_installed
      ignore_errors: yes
      tags: [always]

    - name: create the fact idm_is_installed
      set_fact:
        idm_is_installed: "{{ False if idm_is_installed.failed | default(False) or idm_is_installed.status != 200 else True }}"
      tags: [always]

    - name: Ensure the KVM host is not pointing to the IdM server for DNS
      copy:
        content: |
          search {{ search_domains  | first }}
          nameserver 8.8.8.8
          nameserver 1.1.1.1
        dest: /etc/resolv.conf
      when: not idm_is_installed
      tags: [ipaserver, resolv]

    - name: Declare the repos for IdM
      set_fact:
        rhsm_repos: "{{ idm_repos_8 }}"
      when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == '8')
      tags: [ipaserver]

    - name: ensure system is registered to Red Hat
      include_role:
        name: swygue-redhat-subscription
      when: not idm_is_installed or force_idm_redeployment|bool
      tags: [rhsm, ipaserver]

    - name: Deploy the IdM server
      tags: [ipaserver]
      when:
        - not idm_is_installed or force_idm_redeployment|bool
      block:
        - name: ensure ansible-freeipa is installed
          ansible.builtin.git:
            repo: 'https://github.com/freeipa/ansible-freeipa.git'
            dest: "{{ playbook_dir }}/roles/ansible-freeipa"
            version: master
          delegate_to: 127.0.0.1
          become: yes
          tags: ansiblefreeipa

        - name: Running the ipaserver role
          include_role:
            name: ipaserver
          vars:
            - ipaserver_domain: "{{ domain }}"
            - idm_realm: "{{ domain | upper }}"
            - ipaserver_realm: "{{ idm_realm }}"
            - ipaserver_setup_dns: "yes"
            - ipaserver_no_host_dns: yes
            - ipaserver_setup_kra: yes
            - ipaserver_forwarders:
              - "{{ dns_forwarder }}"
            - ipaserver_reverse_zones: "{{ idm_reverse_zones }}"
            - ipaadmin_password: "{{ idm_admin_password }}"
            - ipadm_password: "{{ idm_dm_pwd }}"

    - name: update KVM host /etc/resolv.conf to point to the IdM server {{ vm_name }}
      vars:
        ansible_python_interpreter: /usr/bin/python3
      copy:
        content: |
          search {{ search_domains  | first }}
          nameserver {{ idm_server_ip }}
        dest: /etc/resolv.conf
      when: 
        - not force_idm_redeployment|bool and not vm_teardown|bool
      delegate_to: 127.0.0.1
