---
- name: Download OpenShift 4 installer
  hosts: localhost
  vars_files:
    - vars/all.yml
    - vars/vault.yml
    - vars/idm.yml
    - vars/ocp4.yml
  become: yes

  tasks:
  - name: Remove openshift client cli
    command: rm -rf /usr/local/bin/oc
    when: remove_oc_tool

  - name: Remove  openshift installer
    command: rm -rf  /usr/local/bin/openshift-install
    when: remove_oc_tool

  - name: Download OpenShift 4 client
    get_url:
      url: "{{ ocp4_release_url }}/{{ ocp4_client }}"
      dest: "/tmp/{{ ocp4_client }}"

  - name: Download OpenShift 4 installer
    get_url:
      url: "{{ ocp4_release_url }}/{{ ocp4_installer }}"
      dest: "/tmp/{{ ocp4_installer }}"

  - name: Extract ocp client  into /usr/local/bin/oc
    unarchive:
      src: "/tmp/{{ ocp4_client }}"
      dest: /usr/local/bin

  - name: Extract openshift installer into /usr/local/bin/openshift-install
    unarchive:
      src:  "/tmp/{{ ocp4_installer }}"
      dest:  /usr/local/bin
  - name: Remove openshift client tar file
    command: rm -rf "/tmp/{{ ocp4_client }}"
  - name: Remove openshift installer  tar file
    command: rm -rf "/tmp/{{ ocp4_installer }}"
