- name: configure openshift IdM auth
  hosts: localhost
  become: no
  gather_facts: no
  vars_files:
    - vars/all.yml
    - vars/kvm_host.yml
    - vars/vault.yml
    - vars/idm.yml
    - vars/ocp4.yml
  vars:
    dn_attribute: []
    homedir: "{{ lookup('env','HOME') }}"
    bind_user_pass: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
    vault_pass_file: "{{ homedir }}/.vaultkey"
    vault_file: "{{ project_dir }}/playbooks/vars/vault.yml"

  environment:
    IPA_HOST: "{{ ipa_host }}"
    IPA_USER: "{{ idm_admin_user }}"
    IPA_PASS: "{{ idm_admin_pwd }}"
    IPA_TIMEOUT: 40

  tasks:
    - name: ensure package python3-passlib installed
      package:
        name: python3-passlib
        state: present
      become: yes

    - name: setup IdM distinguished name
      vars:
        - random_pass: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
        - generated_pass: "student{{ item }}"
        - student: "{{ 'student%02d' | format(item|int) }}"
      htpasswd:
        path: "{{ project_dir }}/htpasswd_users"
        name: "{{ student }}"
        password: "{{ student }}"
        owner: "{{ admin_user }}"
        mode: 0640
      loop: "{{ range(0, 20 + 1)|list }}"

    - name: check if htpasswd secret exist
      shell: oc get secret -n openshift-config | grep htpasswd-secret
      register: htpasswd_secret_exist
      ignore_errors: yes
      changed_when: False

    - name: create openshift htpasswd secret
      command: oc create secret generic htpass-secret --from-file=htpasswd={{ project_dir }}/htpasswd_users -n openshift-config
      register: create_htpasswd_secret
      changed_when: False
      when: htpasswd_secret_exist.rc != 0

    - name: create htpasswd customer resource
      vars:
        - htpasswd_cr: |
            apiVersion: config.openshift.io/v1
            kind: OAuth
            metadata:
              name: cluster
            spec:
              identityProviders:
              - name: {{ instance_prefix }}_htpasswd_provider
                mappingMethod: claim
                type: HTPasswd
                htpasswd:
                  fileData:
                    name: htpass-secret
      shell: |
        cat > /tmp/htpasswd_csr <<EOF
        {{ htpasswd_cr }}
        EOF
        oc apply -f /tmp/htpasswd_csr
