- name: confirm that you can reach the each node in cluster
  vars:
    vm_name: "{{ preappend_host_name }}{{ outer_item.name }}{{ '%02x' |format(inner_item) }}"
    vm_group: "{{ outer_item.role_group }}"
  shell: ping {{ vm_name }}.{{ domain }} -c 1
  loop: "{{ range(1, outer_item.qty|int +1)|list }}"
  loop_control:
    loop_var: inner_item
    label: "{{ vm_name }}"
  register: ping_nodes_result
  changed_when: false
  ignore_errors: no


- name: Check if registry.redhat.io resolves
  shell: |
      dig +short -t a registry.redhat.io| head -1
  register: registry_redhat_io
  ignore_errors: no
  changed_when: false

#- name: Check that the dns wildcard resolves
#  shell: |
#      dig +short "{{ dns_wildcard }}.{{ domain }}"| head -1
#  register: dns_wildcard
#  ignore_errors: no

- name: test connectivity to registry.redhat.io
  shell: |
      ping registry.redhat.io -c1
  register: ping_registry_redhat_io
  until: ('0% packet loss' in ping_registry_redhat_io.stdout)
  failed_when: ('100.0% packet loss' in ping_registry_redhat_io.stdout)
  retries: 10
  delay: 3

- name: "Check that all required packages are installed"
  shell: yum list installed | awk '{print $1}'  | cut -f1 -d"."
  register: pkg_result

- local_action: copy content={{ pkg_result.stdout  }} dest=/tmp/{{ inventory_hostname }}

- name: confirm required packages are installed on nodes
  vars:
    vm_name: "{{ preappend_host_name }}{{ outer_item.name }}0{{ item.1 }}"
    vm_group: "{{ outer_item.role_group }}"
  shell: "cat /tmp/{{ vm_name }} | grep {{ item.0 }}"
  register: pkg_install_status
  changed_when: false
  with_nested:
    - "{{ ocp_nodes_pkgs }}"
    - "{{ range(1, outer_item.qty|int +1)|list }}"
  ignore_errors: no
  delegate_to: localhost
