- name: configure openshift IdM auth
  hosts: localhost
  become: no
  gather_facts: no
  vars_files:
    - vars/all.yml
    - vars/kvm_host.yml
    - vars/vault.yml
    - vars/idm.yml
    - vars/ocp4.yml
  vars:
    idm_group_desc: "A group of students"
    idm_group: student
    idm_group_state: present
    idm_group_type_posix: no
    idm_group_users: []
    idm_user_generated_prefix: student
    user_name_format: "{{ idm_user_generated_prefix }}%02d"
    total_users: 4
    idm_user_pass_expiration: 20200119235959
    idm_user_state: present
    idm_user_shell: "/usr/bin/bash"
    idm_user_sn: "learner"
    update_idm_user_pass: on_create
    create_students: yes
    idm_users:
     - name: clusteradmin
       groups:
         - openshift-admin
       password: clusteradmin
       givenname: OpenShift
       sn: Clusteradmin
       state: present
       loginshell: /usr/sbin/nologin
       krbpasswordexpiration: "{{ idm_user_pass_expiration | int}}"
       mail: []
       telephonenumber: []
       sshpubkey: []
       update_password: "{{ update_idm_user_pass }}"
     - name: clusterviewer
       groups:
         - openshift-viewer
       password: clusterviewer
       givenname: OpenShift
       sn: Clusterviewer
       state: present
       loginshell: /usr/sbin/nologin
       krbpasswordexpiration: "{{ idm_user_pass_expiration | int}}"
       mail: []
       telephonenumber: []
       sshpubkey: []
       update_password: "{{ update_idm_user_pass }}"
     - name: "{{ admin_user }}"
       groups:
         - satellite-admin
         - tower-admin
         - openshift-admin
       password: "{{ admin_user }}"
       givenname: "Admin"
       sn: User
       state: present
       loginshell: /usr/bin/bash
       krbpasswordexpiration: "{{ idm_user_pass_expiration | int}}"
       mail: []
       telephonenumber: []
       sshpubkey:
         - "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
         #- "{{ lookup('file', 'files/'+ item.username + '.key.pub') }}"
       update_password: "{{ update_idm_user_pass }}"
  environment:
    IPA_HOST: "{{ ipa_host }}"
    IPA_USER: "{{ idm_admin_user }}"
    IPA_PASS: "{{ idm_admin_pwd }}"
    IPA_TIMEOUT: 40

  tasks:
    - name: create user accounts
      vars:
        idm_user_name: "{{ user_name_format | format(item|int) }}"
      ipa_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        givenname: "{{ item.givenname }}"
        sn: "{{ item.sn }}"
        state: "{{ item.state }}"
        loginshell: "{{ item.loginshell }}"
        krbpasswordexpiration: "{{ item.krbpasswordexpiration }}"
        mail: "{{ item.mail }}"
        telephonenumber: "{{ item.telephonenumber }}"
        sshpubkey: "{{ item.sshpubkey }}"
        update_password: "{{ item.update_password }}"
        validate_certs: no
      #no_log: True
      loop: "{{ idm_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: create groups with users
      ipa_group:
        name: "{{ item.1 }}"
        state: "{{ idm_group_state }}"
        nonposix: "{{ idm_group_type_posix }}"
        description: "{{ idm_group_desc }}"
        user: "{{ item.0.name | default(omit) }}"
        validate_certs: no
      loop: "{{ idm_users|subelements('groups') }}"
      loop_control:
        label: "{{ item.1 }}"

    - name: create student accounts
      when: create_students|bool
      block:
        - name: create {{ total_users }} auto generated users
          vars:
            idm_user_name: "{{ user_name_format | format(item|int) }}"
          ipa_user:
            name: "{{ idm_user_name }}"
            password: "{{ idm_user_name }}"
            givenname: "{{ idm_user_name }}"
            sn: "{{ idm_user_sn }}"
            state: "{{ idm_user_state }}"
            loginshell: "{{ idm_user_shell }}"
            krbpasswordexpiration: "{{ idm_user_pass_expiration | int}}"
            mail: "{{ idm_user_email | default(omit) }}"
            telephonenumber: "{{ idm_user_phone | default(omit) }}"
            sshpubkey: "{{ idm_user_sshpubkey | default(omit) }}"
            update_password: "{{ update_idm_user_pass }}"
            validate_certs: no
          no_log: True
          loop: "{{ range(0, total_users + 1)|list }}"

        - name: build list of idm users
          vars:
            idm_user_name: "{{ user_name_format | format(item|int) }}"
          set_fact:
            idm_group_users: "{{ idm_group_users + [ idm_user_name ] }}"
          loop: "{{ range(0, total_users + 1)|list }}"

        - name: create IdM group {{ idm_group }}
          ipa_group:
            name: "{{ idm_group }}"
            state: "{{ idm_group_state }}"
            nonposix: "{{ idm_group_type_posix }}"
            description: "{{ idm_group_desc }}"
            user: "{{ idm_group_users | default(omit) }}"
            validate_certs: no

