---
- name: Deploy or teardown libvirt VM
  hosts: localhost
  become: yes
  gather_facts: yes
  vars_files:
    - vars/all.yml
    - vars/kvm_host.yml
    - vars/vault.yml
    - vars/idm.yml
    - vars/rhel.yml
  vars:
    vm_name: "{{ rhel_server_vm.rhel_name }}"
    vm_cpu: "{{ rhel_server_vm.rhel_vcpu }}"
    vm_memory: "{{ rhel_server_vm.rhel_memory }}"
    vm_root_disk_size: "{{ rhel_server_vm.rhel_root_disk_size }}"
    vm_teardown: "{{ rhel_server_vm.rhel_teardown }}"
    vm_qcow_image:  "{{ cloud_init_vm_image }}"
    vm_recreate: "{{ rhel_server_vm.rhel_recreate }}"
    vm_domain: "{{ domain }}"
    inventory_group: "{{ rhel_server_vm.rhel_group }}"
    extra_storage: "{{ rhel_server_vm.rhel_extra_storage }}"
    enable: "{{ rhel_server_vm.rhel_enable }}"
    current_vm_ip: "{{ hostvars[vm_name]['ansible_host'] }}"
    idm_ca_crt_url: "{{ 'https://' + ipa_host + '/ipa/config/ca.crt' }}"

  environment:
    IPA_HOST: "{{ ipa_host }}"
    IPA_USER: "{{ idm_admin_user }}"
    IPA_PASS: "{{ idm_admin_pwd }}"
    IPA_TIMEOUT: 40

  tasks:
    - name: check if idm server is deployed
      uri:
        url: "{{ idm_ca_crt_url }}"
        validate_certs: no
      register: idm_status

    - name: running removal steps for VM
      when: vm_teardown|bool
      block:
        - name: call the include_idm_records_tasks.yml to remove dns records
          include_tasks: include_idm_records_tasks.yml

        - name: Include deploy-kvm-vm role
          include_role:
            name: deploy-kvm-vm

        - name: REMOVE|ensure {{ vm_name }} is removed from inventory
          lineinfile:
            path: "{{ inventory_file }}"
            regexp: "^{{ vm_name }}"
            state: absent
          when: vm_teardown|bool

    - name: Include deploy-kvm-vm role
      include_role:
        name: deploy-kvm-vm
      when: not vm_teardown|bool

    - meta: refresh_inventory

    - name: call the include_idm_records_tasks.yml to add dns records
      include_tasks: include_idm_records_tasks.yml
      when: not vm_teardown|bool



