- name: OpenShift nfs-provisioner-role
  hosts: localhost
  become: yes
  vars_files:
    - vars/all.yml
    - vars/kvm_host.yml
    - vars/ocp4.yml
    - vars/vault.yml
  gather_facts: true
  tasks:
  - name: Run nfs-provisioner-role
    import_role:
      name: nfs-provisioner-role
